#
# Cookbook:: apache_httpd
# Spec:: config_site
#
# Copyright:: 2021, Ben Hughes, All Rights Reserved.

describe file('/etc/httpd/conf.site.d/netbox_test.conf') do
  it { should exist }
  it { should be_file }
  its('content') { should match '# Generated by Chef' }
  its('content') { should match /<VirtualHost \*:443>/ }
  its('content') { should match %r{    ProxyPass \/ http:\/\/127.0.0.1:8001\/} }
end
