#
# Cookbook:: apache_httpd
# Spec:: config_module
#
# Copyright:: 2021, Ben Hughes, All Rights Reserved.

if os.family.eql?('redhat') && os.release.to_i.eql?(7)
  describe file('/etc/httpd/conf.modules.d/10-wsgi.conf') do
    it { should exist }
    it { should be_file }
    its('content') { should match '# Generated by Chef' }
    its('content') { should match %r{LoadModule wsgi_module modules\/mod_wsgi\.so} }
  end
else
  describe file('/etc/httpd/conf.modules.d/10-wsgi-python3.conf') do
    it { should exist }
    it { should be_file }
    its('content') { should match '# Generated by Chef' }
    its('content') { should match '<IfModule !wsgi_module>' }
    its('content') { should match %r{    LoadModule wsgi_module modules\/mod_wsgi_python3\.so} }
  end
end
