#
# Cookbook:: apache_httpd
# Spec:: config_global
#
# Copyright:: 2021, Ben Hughes, All Rights Reserved.

describe file('/etc/httpd/conf/httpd.conf') do
  it { should exist }
  it { should be_file }
  its('content') { should match '# Generated by Chef' }
  its('content') { should match '    AddDefaultCharset UTF-8' }
  its('content') { should match %r{IncludeOptional conf\.generic\.d\/\*\.conf} }
end
